### ISSUE TITLE
hello!  Why can't I see other people's pictures?  Has anyone encountered this situation？ Many thanks

### ISSUE THREAD

**Issue by ingenyang** [philnash/video-chat#3]

**Comment by ingenyang** [comment]
After the deployment is complete, I only have my own screen and no chatter's screen

**Comment by philnash** [comment]
Hi @ingenyang, thanks for opening an issue.

I just tested the application and it still works for me. Can you explain more in detail what you are trying and what you are seeing? Are you testing with yourself in two browser windows? Do you see any errors in the browser dev tools or the server log?

**Comment by 281307545** [comment]
In socket.io 4.0, the room has change to ES6 Maps
> rooms: Map<Room, Set<SocketId>>

the related codes need to update in index.js

```
var clients = io.sockets.adapter.rooms.get(room)
var numClients = typeof clients !== 'undefined' ? clients.size : 0;
```

**Comment by philnash** [comment]
This repo is pinned to socket.io 2.4.0 right now.

I don't have the time to upgrade Socket.io, but I'll happily take pull requests.

**Comment by philnash** [comment]
This has gone a bit quiet, so I'm going to close the issue.

If there's anything else I can do to help, please re-open and let me know.
